app:
  name: commentservice
  write_timeout: 10
  read_timeout: 10
  connect_timeout: 10
  default_comment_limit: 10

http:
  host: 0.0.0.0
  port: 8081

logging:
  level: debug
  format: text

databases:
  news:
    host: postgres-news
    port: 5432
    username: news
    password: password
    db_name: newsservice
    sslmode: disable
  comments:
    host: postgres-comments
    port: 5432
    username: news
    password: password
    db_name: commentservice
    sslmode: disable


kafka:
  brokers:
    - kafka:9093
  topics:
    comment_input: comments_input
    add_comment: add_comment
    comments: comments

server: ":8081"

routes:
  - name: newsservice
    base_url: http://newsservice:6000
  - name: apigateway
    base_url: http://apigateway:8080
  - name: censorservice
    base_url: http://localhost:5000